// Latin cognate rules (the Language Transfer shortcut): a handful of suffix
// transformations unlock thousands of Spanish words an English speaker
// already owns. Curated lists only — every pair verified, false friends
// (actual, sensible, dormitorio...) deliberately excluded.

export interface CognatePair {
  en: string;
  es: string;
}

export interface CognateRule {
  slug: string;
  /** Display pattern, e.g. "-tion → -ción". */
  pattern: string;
  label: string;
  /** One blunt line: how the rule works. */
  explanation: string;
  /** Gender/stress traps worth one line, or null. */
  caveat: string | null;
  words: CognatePair[];
}

export const COGNATE_RULES: CognateRule[] = [
  {
    slug: 'cion',
    pattern: '-tion → -ción',
    label: 'Nation → nación',
    explanation: 'English -tion becomes -ción. Hundreds of words, all feminine.',
    caveat: 'Always la: la nación, la información. Stress lands on -ción.',
    words: [
      { en: 'nation', es: 'nación' },
      { en: 'information', es: 'información' },
      { en: 'situation', es: 'situación' },
      { en: 'education', es: 'educación' },
      { en: 'conversation', es: 'conversación' },
      { en: 'station', es: 'estación' },
      { en: 'attention', es: 'atención' },
      { en: 'solution', es: 'solución' },
      { en: 'tradition', es: 'tradición' },
      { en: 'condition', es: 'condición' },
      { en: 'direction', es: 'dirección' },
      { en: 'celebration', es: 'celebración' },
      { en: 'invitation', es: 'invitación' },
      { en: 'reaction', es: 'reacción' },
      { en: 'relation', es: 'relación' },
      { en: 'operation', es: 'operación' },
      { en: 'population', es: 'población' },
      { en: 'generation', es: 'generación' },
      { en: 'imagination', es: 'imaginación' },
      { en: 'organization', es: 'organización' },
      { en: 'communication', es: 'comunicación' },
      { en: 'action', es: 'acción' },
    ],
  },
  {
    slug: 'sion',
    pattern: '-sion → -sión',
    label: 'Decision → decisión',
    explanation: 'English -sion keeps its s and gains an accent. All feminine.',
    caveat: 'Always la: la decisión, la televisión.',
    words: [
      { en: 'decision', es: 'decisión' },
      { en: 'television', es: 'televisión' },
      { en: 'occasion', es: 'ocasión' },
      { en: 'passion', es: 'pasión' },
      { en: 'version', es: 'versión' },
      { en: 'mission', es: 'misión' },
      { en: 'session', es: 'sesión' },
      { en: 'profession', es: 'profesión' },
      { en: 'expression', es: 'expresión' },
      { en: 'impression', es: 'impresión' },
      { en: 'conclusion', es: 'conclusión' },
      { en: 'confusion', es: 'confusión' },
      { en: 'explosion', es: 'explosión' },
      { en: 'tension', es: 'tensión' },
      { en: 'division', es: 'división' },
      { en: 'excursion', es: 'excursión' },
    ],
  },
  {
    slug: 'dad',
    pattern: '-ty → -dad',
    label: 'University → universidad',
    explanation: 'English -ty becomes -dad (sometimes -tad). All feminine.',
    caveat: 'Always la: la ciudad, la universidad. A few take -tad: libertad, dificultad.',
    words: [
      { en: 'university', es: 'universidad' },
      { en: 'city', es: 'ciudad' },
      { en: 'reality', es: 'realidad' },
      { en: 'society', es: 'sociedad' },
      { en: 'opportunity', es: 'oportunidad' },
      { en: 'activity', es: 'actividad' },
      { en: 'quality', es: 'calidad' },
      { en: 'quantity', es: 'cantidad' },
      { en: 'capacity', es: 'capacidad' },
      { en: 'community', es: 'comunidad' },
      { en: 'curiosity', es: 'curiosidad' },
      { en: 'difficulty', es: 'dificultad' },
      { en: 'electricity', es: 'electricidad' },
      { en: 'identity', es: 'identidad' },
      { en: 'liberty', es: 'libertad' },
      { en: 'personality', es: 'personalidad' },
      { en: 'possibility', es: 'posibilidad' },
      { en: 'priority', es: 'prioridad' },
      { en: 'responsibility', es: 'responsabilidad' },
      { en: 'security', es: 'seguridad' },
      { en: 'velocity', es: 'velocidad' },
      { en: 'variety', es: 'variedad' },
    ],
  },
  {
    slug: 'al',
    pattern: '-al → -al',
    label: 'Animal → animal',
    explanation: 'Words ending -al usually transfer unchanged. Say them in Spanish.',
    caveat: 'Trap: "actual" means current, not real. Excluded here.',
    words: [
      { en: 'animal', es: 'animal' },
      { en: 'capital', es: 'capital' },
      { en: 'normal', es: 'normal' },
      { en: 'natural', es: 'natural' },
      { en: 'legal', es: 'legal' },
      { en: 'final', es: 'final' },
      { en: 'general', es: 'general' },
      { en: 'hospital', es: 'hospital' },
      { en: 'ideal', es: 'ideal' },
      { en: 'local', es: 'local' },
      { en: 'mental', es: 'mental' },
      { en: 'moral', es: 'moral' },
      { en: 'original', es: 'original' },
      { en: 'personal', es: 'personal' },
      { en: 'principal', es: 'principal' },
      { en: 'social', es: 'social' },
      { en: 'total', es: 'total' },
      { en: 'tropical', es: 'tropical' },
      { en: 'central', es: 'central' },
      { en: 'digital', es: 'digital' },
      { en: 'festival', es: 'festival' },
      { en: 'formal', es: 'formal' },
    ],
  },
  {
    slug: 'ante',
    pattern: '-ant/-ent → -ante/-ente',
    label: 'Important → importante',
    explanation: 'English -ant becomes -ante, -ent becomes -ente.',
    caveat: null,
    words: [
      { en: 'important', es: 'importante' },
      { en: 'different', es: 'diferente' },
      { en: 'elegant', es: 'elegante' },
      { en: 'evident', es: 'evidente' },
      { en: 'excellent', es: 'excelente' },
      { en: 'frequent', es: 'frecuente' },
      { en: 'ignorant', es: 'ignorante' },
      { en: 'intelligent', es: 'inteligente' },
      { en: 'interesting', es: 'interesante' },
      { en: 'permanent', es: 'permanente' },
      { en: 'present', es: 'presente' },
      { en: 'urgent', es: 'urgente' },
      { en: 'client', es: 'cliente' },
      { en: 'accident', es: 'accidente' },
      { en: 'agent', es: 'agente' },
      { en: 'continent', es: 'continente' },
      { en: 'elephant', es: 'elefante' },
      { en: 'instant', es: 'instante' },
      { en: 'restaurant', es: 'restaurante' },
      { en: 'constant', es: 'constante' },
      { en: 'independent', es: 'independiente' },
      { en: 'patient', es: 'paciente' },
    ],
  },
  {
    slug: 'ble',
    pattern: '-ble → -ble',
    label: 'Possible → posible',
    explanation: '-ible and -able words transfer nearly unchanged (single s, single l).',
    caveat: 'Trap: "sensible" means sensitive. Excluded here.',
    words: [
      { en: 'possible', es: 'posible' },
      { en: 'impossible', es: 'imposible' },
      { en: 'probable', es: 'probable' },
      { en: 'terrible', es: 'terrible' },
      { en: 'horrible', es: 'horrible' },
      { en: 'admirable', es: 'admirable' },
      { en: 'adorable', es: 'adorable' },
      { en: 'cable', es: 'cable' },
      { en: 'comparable', es: 'comparable' },
      { en: 'considerable', es: 'considerable' },
      { en: 'favorable', es: 'favorable' },
      { en: 'flexible', es: 'flexible' },
      { en: 'inevitable', es: 'inevitable' },
      { en: 'invisible', es: 'invisible' },
      { en: 'memorable', es: 'memorable' },
      { en: 'miserable', es: 'miserable' },
      { en: 'noble', es: 'noble' },
      { en: 'notable', es: 'notable' },
      { en: 'responsible', es: 'responsable' },
      { en: 'visible', es: 'visible' },
    ],
  },
  {
    slug: 'ico',
    pattern: '-ic/-ical → -ico',
    label: 'Fantastic → fantástico',
    explanation: 'English -ic and -ical both become -ico, accent on the syllable before.',
    caveat: 'The written accent is part of the word: fantástico, lógico.',
    words: [
      { en: 'fantastic', es: 'fantástico' },
      { en: 'romantic', es: 'romántico' },
      { en: 'logical', es: 'lógico' },
      { en: 'political', es: 'político' },
      { en: 'public', es: 'público' },
      { en: 'basic', es: 'básico' },
      { en: 'classic', es: 'clásico' },
      { en: 'comic', es: 'cómico' },
      { en: 'dramatic', es: 'dramático' },
      { en: 'economic', es: 'económico' },
      { en: 'electric', es: 'eléctrico' },
      { en: 'specific', es: 'específico' },
      { en: 'historic', es: 'histórico' },
      { en: 'identical', es: 'idéntico' },
      { en: 'magic', es: 'mágico' },
      { en: 'organic', es: 'orgánico' },
      { en: 'plastic', es: 'plástico' },
      { en: 'practical', es: 'práctico' },
      { en: 'typical', es: 'típico' },
      { en: 'traffic', es: 'tráfico' },
      { en: 'authentic', es: 'auténtico' },
      { en: 'artistic', es: 'artístico' },
    ],
  },
  {
    slug: 'oso',
    pattern: '-ous → -oso',
    label: 'Famous → famoso',
    explanation: 'English -ous becomes -oso (or -osa describing feminine nouns).',
    caveat: null,
    words: [
      { en: 'famous', es: 'famoso' },
      { en: 'delicious', es: 'delicioso' },
      { en: 'curious', es: 'curioso' },
      { en: 'nervous', es: 'nervioso' },
      { en: 'generous', es: 'generoso' },
      { en: 'ambitious', es: 'ambicioso' },
      { en: 'contagious', es: 'contagioso' },
      { en: 'furious', es: 'furioso' },
      { en: 'glorious', es: 'glorioso' },
      { en: 'mysterious', es: 'misterioso' },
      { en: 'numerous', es: 'numeroso' },
      { en: 'precious', es: 'precioso' },
      { en: 'religious', es: 'religioso' },
      { en: 'victorious', es: 'victorioso' },
      { en: 'tedious', es: 'tedioso' },
      { en: 'fabulous', es: 'fabuloso' },
    ],
  },
  {
    slug: 'encia',
    pattern: '-ence/-ance → -encia/-ancia',
    label: 'Experience → experiencia',
    explanation: 'English -ence becomes -encia, -ance becomes -ancia. All feminine.',
    caveat: 'Always la: la experiencia, la importancia.',
    words: [
      { en: 'experience', es: 'experiencia' },
      { en: 'importance', es: 'importancia' },
      { en: 'distance', es: 'distancia' },
      { en: 'difference', es: 'diferencia' },
      { en: 'elegance', es: 'elegancia' },
      { en: 'emergency', es: 'emergencia' },
      { en: 'evidence', es: 'evidencia' },
      { en: 'existence', es: 'existencia' },
      { en: 'independence', es: 'independencia' },
      { en: 'intelligence', es: 'inteligencia' },
      { en: 'patience', es: 'paciencia' },
      { en: 'preference', es: 'preferencia' },
      { en: 'presence', es: 'presencia' },
      { en: 'residence', es: 'residencia' },
      { en: 'violence', es: 'violencia' },
      { en: 'ambulance', es: 'ambulancia' },
      { en: 'consequence', es: 'consecuencia' },
      { en: 'frequency', es: 'frecuencia' },
      { en: 'influence', es: 'influencia' },
      { en: 'reference', es: 'referencia' },
      { en: 'tolerance', es: 'tolerancia' },
      { en: 'abundance', es: 'abundancia' },
    ],
  },
  {
    slug: 'ista',
    pattern: '-ist/-ism → -ista/-ismo',
    label: 'Artist → artista',
    explanation: 'English -ist becomes -ista (people), -ism becomes -ismo (ideas).',
    caveat: '-ista words keep -a for both genders: el artista, la artista.',
    words: [
      { en: 'artist', es: 'artista' },
      { en: 'tourist', es: 'turista' },
      { en: 'dentist', es: 'dentista' },
      { en: 'pianist', es: 'pianista' },
      { en: 'optimist', es: 'optimista' },
      { en: 'pessimist', es: 'pesimista' },
      { en: 'realist', es: 'realista' },
      { en: 'specialist', es: 'especialista' },
      { en: 'guitarist', es: 'guitarrista' },
      { en: 'economist', es: 'economista' },
      { en: 'tourism', es: 'turismo' },
      { en: 'optimism', es: 'optimismo' },
      { en: 'pessimism', es: 'pesimismo' },
      { en: 'realism', es: 'realismo' },
      { en: 'capitalism', es: 'capitalismo' },
      { en: 'socialism', es: 'socialismo' },
      { en: 'mechanism', es: 'mecanismo' },
      { en: 'organism', es: 'organismo' },
      { en: 'racism', es: 'racismo' },
    ],
  },
  {
    slug: 'ivo',
    pattern: '-ive → -ivo',
    label: 'Positive → positivo',
    explanation: 'English -ive becomes -ivo (-iva describing feminine nouns).',
    caveat: null,
    words: [
      { en: 'positive', es: 'positivo' },
      { en: 'negative', es: 'negativo' },
      { en: 'active', es: 'activo' },
      { en: 'creative', es: 'creativo' },
      { en: 'attractive', es: 'atractivo' },
      { en: 'competitive', es: 'competitivo' },
      { en: 'defensive', es: 'defensivo' },
      { en: 'definitive', es: 'definitivo' },
      { en: 'exclusive', es: 'exclusivo' },
      { en: 'expressive', es: 'expresivo' },
      { en: 'festive', es: 'festivo' },
      { en: 'motive', es: 'motivo' },
      { en: 'objective', es: 'objetivo' },
      { en: 'productive', es: 'productivo' },
      { en: 'progressive', es: 'progresivo' },
      { en: 'relative', es: 'relativo' },
      { en: 'aggressive', es: 'agresivo' },
      { en: 'alternative', es: 'alternativo' },
      { en: 'executive', es: 'ejecutivo' },
    ],
  },
  {
    slug: 'ario',
    pattern: '-ary/-ory → -ario/-orio',
    label: 'Necessary → necesario',
    explanation: 'English -ary becomes -ario, -ory becomes -orio.',
    caveat: 'Trap: dormitorio means bedroom, not dormitory. Excluded here.',
    words: [
      { en: 'necessary', es: 'necesario' },
      { en: 'ordinary', es: 'ordinario' },
      { en: 'salary', es: 'salario' },
      { en: 'vocabulary', es: 'vocabulario' },
      { en: 'dictionary', es: 'diccionario' },
      { en: 'anniversary', es: 'aniversario' },
      { en: 'canary', es: 'canario' },
      { en: 'contrary', es: 'contrario' },
      { en: 'diary', es: 'diario' },
      { en: 'extraordinary', es: 'extraordinario' },
      { en: 'imaginary', es: 'imaginario' },
      { en: 'secretary', es: 'secretario' },
      { en: 'voluntary', es: 'voluntario' },
      { en: 'territory', es: 'territorio' },
      { en: 'laboratory', es: 'laboratorio' },
      { en: 'observatory', es: 'observatorio' },
      { en: 'obligatory', es: 'obligatorio' },
    ],
  },
  {
    slug: 'mente',
    pattern: '-ly → -mente',
    label: 'Exactly → exactamente',
    explanation:
      'English -ly becomes -mente: take the adjective (feminine form) and glue -mente on. Instant adverbs.',
    caveat: 'Built on the feminine adjective: perfecta → perfectamente. Written accents survive: rápidamente.',
    words: [
      { en: 'exactly', es: 'exactamente' },
      { en: 'normally', es: 'normalmente' },
      { en: 'probably', es: 'probablemente' },
      { en: 'totally', es: 'totalmente' },
      { en: 'finally', es: 'finalmente' },
      { en: 'generally', es: 'generalmente' },
      { en: 'especially', es: 'especialmente' },
      { en: 'personally', es: 'personalmente' },
      { en: 'really', es: 'realmente' },
      { en: 'naturally', es: 'naturalmente' },
      { en: 'perfectly', es: 'perfectamente' },
      { en: 'completely', es: 'completamente' },
      { en: 'immediately', es: 'inmediatamente' },
      { en: 'frequently', es: 'frecuentemente' },
      { en: 'constantly', es: 'constantemente' },
      { en: 'directly', es: 'directamente' },
      { en: 'correctly', es: 'correctamente' },
      { en: 'possibly', es: 'posiblemente' },
      { en: 'rapidly', es: 'rápidamente' },
      { en: 'simply', es: 'simplemente' },
    ],
  },
  {
    slug: 'ar',
    pattern: '-ate → -ar',
    label: 'Celebrate → celebrar',
    explanation: 'English -ate verbs become -ar verbs. The biggest verb unlock there is.',
    caveat: 'These are infinitives — drive them with quiero / puedo / voy a and speak in full sentences today.',
    words: [
      { en: 'celebrate', es: 'celebrar' },
      { en: 'communicate', es: 'comunicar' },
      { en: 'participate', es: 'participar' },
      { en: 'investigate', es: 'investigar' },
      { en: 'decorate', es: 'decorar' },
      { en: 'calculate', es: 'calcular' },
      { en: 'concentrate', es: 'concentrar' },
      { en: 'negotiate', es: 'negociar' },
      { en: 'operate', es: 'operar' },
      { en: 'evaluate', es: 'evaluar' },
      { en: 'eliminate', es: 'eliminar' },
      { en: 'terminate', es: 'terminar' },
      { en: 'donate', es: 'donar' },
      { en: 'imitate', es: 'imitar' },
      { en: 'indicate', es: 'indicar' },
      { en: 'complicate', es: 'complicar' },
      { en: 'accelerate', es: 'acelerar' },
      { en: 'activate', es: 'activar' },
      { en: 'create', es: 'crear' },
      { en: 'educate', es: 'educar' },
      { en: 'separate', es: 'separar' },
      { en: 'cooperate', es: 'cooperar' },
    ],
  },
  {
    slug: 'ificar',
    pattern: '-ify → -ificar',
    label: 'Identify → identificar',
    explanation: 'English -ify verbs become -ificar.',
    caveat: null,
    words: [
      { en: 'identify', es: 'identificar' },
      { en: 'verify', es: 'verificar' },
      { en: 'justify', es: 'justificar' },
      { en: 'simplify', es: 'simplificar' },
      { en: 'classify', es: 'clasificar' },
      { en: 'clarify', es: 'clarificar' },
      { en: 'modify', es: 'modificar' },
      { en: 'notify', es: 'notificar' },
      { en: 'purify', es: 'purificar' },
      { en: 'unify', es: 'unificar' },
      { en: 'certify', es: 'certificar' },
      { en: 'specify', es: 'especificar' },
      { en: 'intensify', es: 'intensificar' },
      { en: 'qualify', es: 'calificar' },
    ],
  },
  {
    slug: 'izar',
    pattern: '-ize → -izar',
    label: 'Organize → organizar',
    explanation: 'English -ize verbs become -izar.',
    caveat: 'Trap: realizar means to carry out. To realise (notice) is darse cuenta.',
    words: [
      { en: 'organize', es: 'organizar' },
      { en: 'memorize', es: 'memorizar' },
      { en: 'analyze', es: 'analizar' },
      { en: 'utilize', es: 'utilizar' },
      { en: 'authorize', es: 'autorizar' },
      { en: 'characterize', es: 'caracterizar' },
      { en: 'civilize', es: 'civilizar' },
      { en: 'economize', es: 'economizar' },
      { en: 'generalize', es: 'generalizar' },
      { en: 'legalize', es: 'legalizar' },
      { en: 'localize', es: 'localizar' },
      { en: 'modernize', es: 'modernizar' },
      { en: 'normalize', es: 'normalizar' },
      { en: 'paralyze', es: 'paralizar' },
      { en: 'prioritize', es: 'priorizar' },
      { en: 'realize (carry out)', es: 'realizar' },
      { en: 'socialize', es: 'socializar' },
      { en: 'symbolize', es: 'simbolizar' },
    ],
  },
  {
    slug: 'cionverb',
    pattern: '-ción → -ar',
    label: 'Invitación → invitar',
    explanation:
      'Every -ción noun you know hides a verb: strip -ción, add -r. Invitación → invitar. Your noun list is secretly a verb list.',
    caveat: 'Works in reverse too — meet a new verb, and you probably know its -ción noun already.',
    words: [
      { en: 'inform', es: 'informar' },
      { en: 'invite', es: 'invitar' },
      { en: 'confirm', es: 'confirmar' },
      { en: 'reserve', es: 'reservar' },
      { en: 'converse', es: 'conversar' },
      { en: 'observe', es: 'observar' },
      { en: 'imagine', es: 'imaginar' },
      { en: 'declare', es: 'declarar' },
      { en: 'explore', es: 'explorar' },
      { en: 'compare', es: 'comparar' },
      { en: 'prepare', es: 'preparar' },
      { en: 'consider', es: 'considerar' },
      { en: 'continue', es: 'continuar' },
      { en: 'form', es: 'formar' },
    ],
  },
  {
    slug: 'mento',
    pattern: '-ment → -mento',
    label: 'Moment → momento',
    explanation: 'English -ment usually becomes -mento.',
    caveat: 'Not universal: government is gobierno. When in doubt, try it — most land.',
    words: [
      { en: 'moment', es: 'momento' },
      { en: 'document', es: 'documento' },
      { en: 'monument', es: 'monumento' },
      { en: 'instrument', es: 'instrumento' },
      { en: 'apartment', es: 'apartamento' },
      { en: 'argument', es: 'argumento' },
      { en: 'element', es: 'elemento' },
      { en: 'experiment', es: 'experimento' },
      { en: 'fragment', es: 'fragmento' },
      { en: 'cement', es: 'cemento' },
      { en: 'department', es: 'departamento' },
      { en: 'supplement', es: 'suplemento' },
      { en: 'complement', es: 'complemento' },
      { en: 'temperament', es: 'temperamento' },
    ],
  },
  {
    slug: 'ura',
    pattern: '-ure → -ura',
    label: 'Culture → cultura',
    explanation: 'English -ure becomes -ura. All feminine.',
    caveat: 'Always la: la cultura, la temperatura. Trap: nature is la naturaleza.',
    words: [
      { en: 'culture', es: 'cultura' },
      { en: 'temperature', es: 'temperatura' },
      { en: 'structure', es: 'estructura' },
      { en: 'adventure', es: 'aventura' },
      { en: 'agriculture', es: 'agricultura' },
      { en: 'figure', es: 'figura' },
      { en: 'literature', es: 'literatura' },
      { en: 'miniature', es: 'miniatura' },
      { en: 'sculpture', es: 'escultura' },
      { en: 'architecture', es: 'arquitectura' },
      { en: 'creature', es: 'criatura' },
      { en: 'cure', es: 'cura' },
      { en: 'torture', es: 'tortura' },
      { en: 'texture', es: 'textura' },
      { en: 'caricature', es: 'caricatura' },
      { en: 'fracture', es: 'fractura' },
      { en: 'capture', es: 'captura' },
      { en: 'censure', es: 'censura' },
    ],
  },
  {
    slug: 'ido',
    pattern: '-id → -ido',
    label: 'Rapid → rápido',
    explanation: 'English -id adjectives become -ido.',
    caveat: 'The stress usually jumps forward with a written accent: rápido, sólido, tímido.',
    words: [
      { en: 'rapid', es: 'rápido' },
      { en: 'stupid', es: 'estúpido' },
      { en: 'solid', es: 'sólido' },
      { en: 'liquid', es: 'líquido' },
      { en: 'valid', es: 'válido' },
      { en: 'arid', es: 'árido' },
      { en: 'timid', es: 'tímido' },
      { en: 'rigid', es: 'rígido' },
      { en: 'splendid', es: 'espléndido' },
      { en: 'acid', es: 'ácido' },
      { en: 'lucid', es: 'lúcido' },
      { en: 'vivid', es: 'vívido' },
      { en: 'fluid', es: 'fluido' },
      { en: 'invalid', es: 'inválido' },
      { en: 'intrepid', es: 'intrépido' },
    ],
  },
  {
    slug: 'or',
    pattern: '-or → -or',
    label: 'Doctor → doctor',
    explanation: 'Words ending -or transfer unchanged. Just say them in Spanish.',
    caveat: 'Stress moves to the end: docTOR, coLOR, erROR.',
    words: [
      { en: 'doctor', es: 'doctor' },
      { en: 'actor', es: 'actor' },
      { en: 'color', es: 'color' },
      { en: 'error', es: 'error' },
      { en: 'favor', es: 'favor' },
      { en: 'honor', es: 'honor' },
      { en: 'humor', es: 'humor' },
      { en: 'motor', es: 'motor' },
      { en: 'terror', es: 'terror' },
      { en: 'tumor', es: 'tumor' },
      { en: 'factor', es: 'factor' },
      { en: 'sector', es: 'sector' },
      { en: 'vigor', es: 'vigor' },
      { en: 'rumor', es: 'rumor' },
      { en: 'horror', es: 'horror' },
      { en: 'inferior', es: 'inferior' },
      { en: 'superior', es: 'superior' },
      { en: 'interior', es: 'interior' },
      { en: 'exterior', es: 'exterior' },
      { en: 'rigor', es: 'rigor' },
    ],
  },
  {
    slug: 'es',
    pattern: 's + consonant → es-',
    label: 'Special → especial',
    explanation:
      'Spanish never starts a word with s + consonant — it adds e- in front. Hear "es" at the start and strip it to find the English word.',
    caveat: 'Recognition superpower: estrés, espectacular, estadio all hide familiar words.',
    words: [
      { en: 'special', es: 'especial' },
      { en: 'style', es: 'estilo' },
      { en: 'stomach', es: 'estómago' },
      { en: 'statue', es: 'estatua' },
      { en: 'strict', es: 'estricto' },
      { en: 'stable', es: 'estable' },
      { en: 'spectacular', es: 'espectacular' },
      { en: 'spirit', es: 'espíritu' },
      { en: 'student', es: 'estudiante' },
      { en: 'study', es: 'estudiar' },
      { en: 'stress', es: 'estrés' },
      { en: 'scale', es: 'escala' },
      { en: 'space', es: 'espacio' },
      { en: 'school', es: 'escuela' },
      { en: 'ski', es: 'esquí' },
      { en: 'scene', es: 'escena' },
      { en: 'stadium', es: 'estadio' },
      { en: 'strategy', es: 'estrategia' },
    ],
  },
];

export function cognateRule(slug: string): CognateRule | undefined {
  return COGNATE_RULES.find((r) => r.slug === slug);
}

export const COGNATE_WORD_COUNT = COGNATE_RULES.reduce((n, r) => n + r.words.length, 0);
