// Latin cognate rules (the Language Transfer shortcut): a handful of suffix
// transformations unlock thousands of Spanish words an English speaker
// already owns. Curated lists only — every pair verified, false friends
// (actual, sensible, dormitorio...) deliberately excluded.

export interface CognatePair {
  en: string;
  es: string;
}

export interface CognateRule {
  slug: string;
  /** Display pattern, e.g. "-tion → -ción". */
  pattern: string;
  label: string;
  /** One blunt line: how the rule works. */
  explanation: string;
  /** Gender/stress traps worth one line, or null. */
  caveat: string | null;
  words: CognatePair[];
}

export const COGNATE_RULES: CognateRule[] = [
  {
    slug: 'cion',
    pattern: '-tion → -ción',
    label: 'Nation → nación',
    explanation: 'English -tion becomes -ción. Hundreds of words, all feminine.',
    caveat: 'Always la: la nación, la información. Stress lands on -ción.',
    words: [
      { en: 'nation', es: 'nación' },
      { en: 'information', es: 'información' },
      { en: 'situation', es: 'situación' },
      { en: 'education', es: 'educación' },
      { en: 'conversation', es: 'conversación' },
      { en: 'station', es: 'estación' },
      { en: 'attention', es: 'atención' },
      { en: 'solution', es: 'solución' },
      { en: 'tradition', es: 'tradición' },
      { en: 'condition', es: 'condición' },
      { en: 'direction', es: 'dirección' },
      { en: 'celebration', es: 'celebración' },
      { en: 'invitation', es: 'invitación' },
      { en: 'reaction', es: 'reacción' },
      { en: 'relation', es: 'relación' },
      { en: 'operation', es: 'operación' },
      { en: 'population', es: 'población' },
      { en: 'generation', es: 'generación' },
      { en: 'imagination', es: 'imaginación' },
      { en: 'organization', es: 'organización' },
      { en: 'communication', es: 'comunicación' },
      { en: 'action', es: 'acción' },
    ],
  },
  {
    slug: 'sion',
    pattern: '-sion → -sión',
    label: 'Decision → decisión',
    explanation: 'English -sion keeps its s and gains an accent. All feminine.',
    caveat: 'Always la: la decisión, la televisión.',
    words: [
      { en: 'decision', es: 'decisión' },
      { en: 'television', es: 'televisión' },
      { en: 'occasion', es: 'ocasión' },
      { en: 'passion', es: 'pasión' },
      { en: 'version', es: 'versión' },
      { en: 'mission', es: 'misión' },
      { en: 'session', es: 'sesión' },
      { en: 'profession', es: 'profesión' },
      { en: 'expression', es: 'expresión' },
      { en: 'impression', es: 'impresión' },
      { en: 'conclusion', es: 'conclusión' },
      { en: 'confusion', es: 'confusión' },
      { en: 'explosion', es: 'explosión' },
      { en: 'tension', es: 'tensión' },
      { en: 'division', es: 'división' },
      { en: 'excursion', es: 'excursión' },
    ],
  },
  {
    slug: 'dad',
    pattern: '-ty → -dad',
    label: 'University → universidad',
    explanation: 'English -ty becomes -dad (sometimes -tad). All feminine.',
    caveat: 'Always la: la ciudad, la universidad. A few take -tad: libertad, dificultad.',
    words: [
      { en: 'university', es: 'universidad' },
      { en: 'city', es: 'ciudad' },
      { en: 'reality', es: 'realidad' },
      { en: 'society', es: 'sociedad' },
      { en: 'opportunity', es: 'oportunidad' },
      { en: 'activity', es: 'actividad' },
      { en: 'quality', es: 'calidad' },
      { en: 'quantity', es: 'cantidad' },
      { en: 'capacity', es: 'capacidad' },
      { en: 'community', es: 'comunidad' },
      { en: 'curiosity', es: 'curiosidad' },
      { en: 'difficulty', es: 'dificultad' },
      { en: 'electricity', es: 'electricidad' },
      { en: 'identity', es: 'identidad' },
      { en: 'liberty', es: 'libertad' },
      { en: 'personality', es: 'personalidad' },
      { en: 'possibility', es: 'posibilidad' },
      { en: 'priority', es: 'prioridad' },
      { en: 'responsibility', es: 'responsabilidad' },
      { en: 'security', es: 'seguridad' },
      { en: 'velocity', es: 'velocidad' },
      { en: 'variety', es: 'variedad' },
    ],
  },
  {
    slug: 'al',
    pattern: '-al → -al',
    label: 'Animal → animal',
    explanation: 'Words ending -al usually transfer unchanged. Say them in Spanish.',
    caveat: 'Trap: "actual" means current, not real. Excluded here.',
    words: [
      { en: 'animal', es: 'animal' },
      { en: 'capital', es: 'capital' },
      { en: 'normal', es: 'normal' },
      { en: 'natural', es: 'natural' },
      { en: 'legal', es: 'legal' },
      { en: 'final', es: 'final' },
      { en: 'general', es: 'general' },
      { en: 'hospital', es: 'hospital' },
      { en: 'ideal', es: 'ideal' },
      { en: 'local', es: 'local' },
      { en: 'mental', es: 'mental' },
      { en: 'moral', es: 'moral' },
      { en: 'original', es: 'original' },
      { en: 'personal', es: 'personal' },
      { en: 'principal', es: 'principal' },
      { en: 'social', es: 'social' },
      { en: 'total', es: 'total' },
      { en: 'tropical', es: 'tropical' },
      { en: 'central', es: 'central' },
      { en: 'digital', es: 'digital' },
      { en: 'festival', es: 'festival' },
      { en: 'formal', es: 'formal' },
    ],
  },
  {
    slug: 'ante',
    pattern: '-ant/-ent → -ante/-ente',
    label: 'Important → importante',
    explanation: 'English -ant becomes -ante, -ent becomes -ente.',
    caveat: null,
    words: [
      { en: 'important', es: 'importante' },
      { en: 'different', es: 'diferente' },
      { en: 'elegant', es: 'elegante' },
      { en: 'evident', es: 'evidente' },
      { en: 'excellent', es: 'excelente' },
      { en: 'frequent', es: 'frecuente' },
      { en: 'ignorant', es: 'ignorante' },
      { en: 'intelligent', es: 'inteligente' },
      { en: 'interesting', es: 'interesante' },
      { en: 'permanent', es: 'permanente' },
      { en: 'present', es: 'presente' },
      { en: 'urgent', es: 'urgente' },
      { en: 'client', es: 'cliente' },
      { en: 'accident', es: 'accidente' },
      { en: 'agent', es: 'agente' },
      { en: 'continent', es: 'continente' },
      { en: 'elephant', es: 'elefante' },
      { en: 'instant', es: 'instante' },
      { en: 'restaurant', es: 'restaurante' },
      { en: 'constant', es: 'constante' },
      { en: 'independent', es: 'independiente' },
      { en: 'patient', es: 'paciente' },
    ],
  },
  {
    slug: 'ble',
    pattern: '-ble → -ble',
    label: 'Possible → posible',
    explanation: '-ible and -able words transfer nearly unchanged (single s, single l).',
    caveat: 'Trap: "sensible" means sensitive. Excluded here.',
    words: [
      { en: 'possible', es: 'posible' },
      { en: 'impossible', es: 'imposible' },
      { en: 'probable', es: 'probable' },
      { en: 'terrible', es: 'terrible' },
      { en: 'horrible', es: 'horrible' },
      { en: 'admirable', es: 'admirable' },
      { en: 'adorable', es: 'adorable' },
      { en: 'cable', es: 'cable' },
      { en: 'comparable', es: 'comparable' },
      { en: 'considerable', es: 'considerable' },
      { en: 'favorable', es: 'favorable' },
      { en: 'flexible', es: 'flexible' },
      { en: 'inevitable', es: 'inevitable' },
      { en: 'invisible', es: 'invisible' },
      { en: 'memorable', es: 'memorable' },
      { en: 'miserable', es: 'miserable' },
      { en: 'noble', es: 'noble' },
      { en: 'notable', es: 'notable' },
      { en: 'responsible', es: 'responsable' },
      { en: 'visible', es: 'visible' },
    ],
  },
  {
    slug: 'ico',
    pattern: '-ic/-ical → -ico',
    label: 'Fantastic → fantástico',
    explanation: 'English -ic and -ical both become -ico, accent on the syllable before.',
    caveat: 'The written accent is part of the word: fantástico, lógico.',
    words: [
      { en: 'fantastic', es: 'fantástico' },
      { en: 'romantic', es: 'romántico' },
      { en: 'logical', es: 'lógico' },
      { en: 'political', es: 'político' },
      { en: 'public', es: 'público' },
      { en: 'basic', es: 'básico' },
      { en: 'classic', es: 'clásico' },
      { en: 'comic', es: 'cómico' },
      { en: 'dramatic', es: 'dramático' },
      { en: 'economic', es: 'económico' },
      { en: 'electric', es: 'eléctrico' },
      { en: 'specific', es: 'específico' },
      { en: 'historic', es: 'histórico' },
      { en: 'identical', es: 'idéntico' },
      { en: 'magic', es: 'mágico' },
      { en: 'organic', es: 'orgánico' },
      { en: 'plastic', es: 'plástico' },
      { en: 'practical', es: 'práctico' },
      { en: 'typical', es: 'típico' },
      { en: 'traffic', es: 'tráfico' },
      { en: 'authentic', es: 'auténtico' },
      { en: 'artistic', es: 'artístico' },
    ],
  },
  {
    slug: 'oso',
    pattern: '-ous → -oso',
    label: 'Famous → famoso',
    explanation: 'English -ous becomes -oso (or -osa describing feminine nouns).',
    caveat: null,
    words: [
      { en: 'famous', es: 'famoso' },
      { en: 'delicious', es: 'delicioso' },
      { en: 'curious', es: 'curioso' },
      { en: 'nervous', es: 'nervioso' },
      { en: 'generous', es: 'generoso' },
      { en: 'ambitious', es: 'ambicioso' },
      { en: 'contagious', es: 'contagioso' },
      { en: 'furious', es: 'furioso' },
      { en: 'glorious', es: 'glorioso' },
      { en: 'mysterious', es: 'misterioso' },
      { en: 'numerous', es: 'numeroso' },
      { en: 'precious', es: 'precioso' },
      { en: 'religious', es: 'religioso' },
      { en: 'victorious', es: 'victorioso' },
      { en: 'tedious', es: 'tedioso' },
      { en: 'fabulous', es: 'fabuloso' },
    ],
  },
  {
    slug: 'encia',
    pattern: '-ence/-ance → -encia/-ancia',
    label: 'Experience → experiencia',
    explanation: 'English -ence becomes -encia, -ance becomes -ancia. All feminine.',
    caveat: 'Always la: la experiencia, la importancia.',
    words: [
      { en: 'experience', es: 'experiencia' },
      { en: 'importance', es: 'importancia' },
      { en: 'distance', es: 'distancia' },
      { en: 'difference', es: 'diferencia' },
      { en: 'elegance', es: 'elegancia' },
      { en: 'emergency', es: 'emergencia' },
      { en: 'evidence', es: 'evidencia' },
      { en: 'existence', es: 'existencia' },
      { en: 'independence', es: 'independencia' },
      { en: 'intelligence', es: 'inteligencia' },
      { en: 'patience', es: 'paciencia' },
      { en: 'preference', es: 'preferencia' },
      { en: 'presence', es: 'presencia' },
      { en: 'residence', es: 'residencia' },
      { en: 'violence', es: 'violencia' },
      { en: 'ambulance', es: 'ambulancia' },
      { en: 'consequence', es: 'consecuencia' },
      { en: 'frequency', es: 'frecuencia' },
      { en: 'influence', es: 'influencia' },
      { en: 'reference', es: 'referencia' },
      { en: 'tolerance', es: 'tolerancia' },
      { en: 'abundance', es: 'abundancia' },
    ],
  },
  {
    slug: 'ista',
    pattern: '-ist/-ism → -ista/-ismo',
    label: 'Artist → artista',
    explanation: 'English -ist becomes -ista (people), -ism becomes -ismo (ideas).',
    caveat: '-ista words keep -a for both genders: el artista, la artista.',
    words: [
      { en: 'artist', es: 'artista' },
      { en: 'tourist', es: 'turista' },
      { en: 'dentist', es: 'dentista' },
      { en: 'pianist', es: 'pianista' },
      { en: 'optimist', es: 'optimista' },
      { en: 'pessimist', es: 'pesimista' },
      { en: 'realist', es: 'realista' },
      { en: 'specialist', es: 'especialista' },
      { en: 'guitarist', es: 'guitarrista' },
      { en: 'economist', es: 'economista' },
      { en: 'tourism', es: 'turismo' },
      { en: 'optimism', es: 'optimismo' },
      { en: 'pessimism', es: 'pesimismo' },
      { en: 'realism', es: 'realismo' },
      { en: 'capitalism', es: 'capitalismo' },
      { en: 'socialism', es: 'socialismo' },
      { en: 'mechanism', es: 'mecanismo' },
      { en: 'organism', es: 'organismo' },
      { en: 'racism', es: 'racismo' },
    ],
  },
  {
    slug: 'ivo',
    pattern: '-ive → -ivo',
    label: 'Positive → positivo',
    explanation: 'English -ive becomes -ivo (-iva describing feminine nouns).',
    caveat: null,
    words: [
      { en: 'positive', es: 'positivo' },
      { en: 'negative', es: 'negativo' },
      { en: 'active', es: 'activo' },
      { en: 'creative', es: 'creativo' },
      { en: 'attractive', es: 'atractivo' },
      { en: 'competitive', es: 'competitivo' },
      { en: 'defensive', es: 'defensivo' },
      { en: 'definitive', es: 'definitivo' },
      { en: 'exclusive', es: 'exclusivo' },
      { en: 'expressive', es: 'expresivo' },
      { en: 'festive', es: 'festivo' },
      { en: 'motive', es: 'motivo' },
      { en: 'objective', es: 'objetivo' },
      { en: 'productive', es: 'productivo' },
      { en: 'progressive', es: 'progresivo' },
      { en: 'relative', es: 'relativo' },
      { en: 'aggressive', es: 'agresivo' },
      { en: 'alternative', es: 'alternativo' },
      { en: 'executive', es: 'ejecutivo' },
    ],
  },
  {
    slug: 'ario',
    pattern: '-ary/-ory → -ario/-orio',
    label: 'Necessary → necesario',
    explanation: 'English -ary becomes -ario, -ory becomes -orio.',
    caveat: 'Trap: dormitorio means bedroom, not dormitory. Excluded here.',
    words: [
      { en: 'necessary', es: 'necesario' },
      { en: 'ordinary', es: 'ordinario' },
      { en: 'salary', es: 'salario' },
      { en: 'vocabulary', es: 'vocabulario' },
      { en: 'dictionary', es: 'diccionario' },
      { en: 'anniversary', es: 'aniversario' },
      { en: 'canary', es: 'canario' },
      { en: 'contrary', es: 'contrario' },
      { en: 'diary', es: 'diario' },
      { en: 'extraordinary', es: 'extraordinario' },
      { en: 'imaginary', es: 'imaginario' },
      { en: 'secretary', es: 'secretario' },
      { en: 'voluntary', es: 'voluntario' },
      { en: 'territory', es: 'territorio' },
      { en: 'laboratory', es: 'laboratorio' },
      { en: 'observatory', es: 'observatorio' },
      { en: 'obligatory', es: 'obligatorio' },
    ],
  },
];

export function cognateRule(slug: string): CognateRule | undefined {
  return COGNATE_RULES.find((r) => r.slug === slug);
}

export const COGNATE_WORD_COUNT = COGNATE_RULES.reduce((n, r) => n + r.words.length, 0);
